<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <None Update="Fixtures\content-time.json" CopyToOutputDirectory="PreserveNewest" />
    <None Include="..\..\src\TyfloCentrum.Windows.App\Views\NewsSectionView.xaml;..\..\src\TyfloCentrum.Windows.App\Views\ArticleSectionView.xaml;..\..\src\TyfloCentrum.Windows.App\Views\PodcastSectionView.xaml;..\..\src\TyfloCentrum.Windows.App\Views\SearchSectionView.xaml;..\..\src\TyfloCentrum.Windows.App\Views\FavoritesSectionView.xaml;..\..\src\TyfloCentrum.Windows.App\Views\TyfloSwiatMagazineView.xaml" Link="Fixtures\%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\TyfloCentrum.Windows.Domain\TyfloCentrum.Windows.Domain.csproj" />
    <ProjectReference Include="..\..\src\TyfloCentrum.Windows.Infrastructure\TyfloCentrum.Windows.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\TyfloCentrum.Windows.UI\TyfloCentrum.Windows.UI.csproj" />
  </ItemGroup>
</Project>
